### ISSUE TITLE
can't find the CMakelist.txt or msvc project file?

### ISSUE THREAD

**Issue by qicosmos** [ddway2/http2_asio#1]

**Comment by ddway2** [comment]
I use cbuild/cpkg toolchain (https://github.com/ddway2/cbuild) to generate CMakeLists.txt. It is only work on Linux (APT) and MacOS X. But, you can use it with Docker

**Comment by qicosmos** [comment]
@ddway2 can you upload the generated CMakeLists.txt?

**Comment by ddway2** [comment]
Generated CMakeLists.txt is specific to your project (absolute path) and contains packaging processing (dpkg). CBuild generate some specific header file and resolve third party dependencies.
I will create Dockerfile for cbuild asap

**Comment by qicosmos** [comment]
@ddway2 What a pity, i don't know how to use cbuild/cpkg. I just wan't a project file to using the http2_asio.

**Comment by qicosmos** [comment]
@ddway2 The absolute path, i can change, so you could give me the file.
